import {
  Code,
  Palette,
  Megaphone,
  FileText,
  Film,
  Languages,
  Camera,
  Music,
  Sparkles,
  LayoutTemplate,
  Server,
  Smartphone,
  PenTool,
  Layers,
  Share2,
  Play,
  Bug,
  Cloud,
  BarChart3,
  Users,
  Shield,
  Trophy,
  Dumbbell,
  Brush,
  Microscope,
  Calculator,
  Wrench,
  Gamepad2,
  Theater,
  BookOpen,
  HeartPulse,
  Leaf,
  Utensils,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

const CATEGORY_ICON_MAP: Record<string, LucideIcon> = {
  Programming: Code,
  Design: Palette,
  Marketing: Megaphone,
  Copywriting: FileText,
  "Video editing": Film,
  Translation: Languages,
  Photography: Camera,
  "Music & Audio": Music,
  Other: Sparkles,
  "IT и программирование": Code,
  "Дизайн и визуальное искусство": Palette,
  "Живопись и рисунок": Brush,
  "Музыка и вокал": Music,
  "Видео и кино": Film,
  "Фотография": Camera,
  "Писательство и журналистика": FileText,
  "Наука и исследования": Microscope,
  "Математика и олимпиадные задачи": Calculator,
  "Инженерия и робототехника": Wrench,
  "Спорт": Trophy,
  "Футбол": Dumbbell,
  "Танцы и хореография": Music,
  "Театр и актерское мастерство": Theater,
  "Предпринимательство": Users,
  "Маркетинг и SMM": Megaphone,
  "Иностранные языки": Languages,
  "Образование и наставничество": BookOpen,
  "Киберспорт и игры": Gamepad2,
  "Медицина и биология": HeartPulse,
  "Экология и социальные проекты": Leaf,
  "Кулинария": Utensils,
  "Ремесла и handmade": Wrench,
  "Другое": Sparkles,
};

const SPECIALIZATION_ICON_MAP: Record<string, LucideIcon> = {
  "Fullstack Developer": Code,
  "Frontend Developer": LayoutTemplate,
  "Backend Developer": Server,
  "Mobile Developer": Smartphone,
  "UI/UX Designer": Palette,
  "Graphic Designer": PenTool,
  "Product Designer": Layers,
  Marketer: Megaphone,
  "SMM Manager": Share2,
  Copywriter: FileText,
  "Video Editor": Film,
  "Motion Designer": Play,
  Translator: Languages,
  Photographer: Camera,
  "QA Engineer": Bug,
  "DevOps Engineer": Cloud,
  "Data Analyst": BarChart3,
  "Project Manager": Users,
  Other: Sparkles,
  "Футболист": Dumbbell,
  "Вратарь": Shield,
  "Защитник": Shield,
  "Полузащитник": Dumbbell,
  "Нападающий": Trophy,
  "Баскетболист": Trophy,
  "Волейболист": Trophy,
  "Пловец": Trophy,
  "Легкоатлет": Trophy,
  "Шахматист": Sparkles,
  "Художник": Brush,
  "Иллюстратор": PenTool,
  "Графический дизайнер": PenTool,
  "UI/UX дизайнер": Palette,
  "3D-моделлер": Layers,
  "Аниматор": Play,
  "Фотограф": Camera,
  "Видеограф": Film,
  "Монтажер видео": Film,
  "Режиссер": Film,
  "Актер": Theater,
  "Танцор": Music,
  "Хореограф": Music,
  "Музыкант": Music,
  "Вокалист": Music,
  "Композитор": Music,
  "Звукорежиссер": Music,
  "Писатель": FileText,
  "Копирайтер": FileText,
  "Журналист": FileText,
  "Блогер": Share2,
  "SMM-специалист": Share2,
  "Маркетолог": Megaphone,
  "Предприниматель": Users,
  "Frontend-разработчик": LayoutTemplate,
  "Backend-разработчик": Server,
  "Fullstack-разработчик": Code,
  "Мобильный разработчик": Smartphone,
  "Разработчик игр": Gamepad2,
  "AI/ML-разработчик": Code,
  "Data analyst": BarChart3,
  "QA-тестировщик": Bug,
  "Робототехник": Wrench,
  "Инженер-конструктор": Wrench,
  "Математик-олимпиадник": Calculator,
  "Физик-исследователь": Microscope,
  "Химик-исследователь": Microscope,
  "Биолог-исследователь": Microscope,
  "Эколог": Leaf,
  "Переводчик": Languages,
  "Репетитор": BookOpen,
  "Наставник младших школьников": BookOpen,
  "Организатор мероприятий": Users,
  "Социальный проектировщик": Users,
  "Кулинар": Utensils,
  "Мастер handmade": Wrench,
  "Другое": Sparkles,
};

export function getCategoryIcon(name: string): LucideIcon {
  return CATEGORY_ICON_MAP[name] ?? Sparkles;
}

export function getSpecializationIcon(name: string | null | undefined): LucideIcon {
  if (!name) return Sparkles;
  return SPECIALIZATION_ICON_MAP[name] ?? Sparkles;
}
